---
name:             ParticleChase
main:             kim\present\particlechase\ParticleChase
version:          1.2.2
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 4.0.0]
author:           PresentKim
description:      A plugin set particle fallow player

permissions:
  particlechase.cmd:
    description:  ParticleChase main command
    default:      op
    children:
      particlechase.cmd.set:
        description:  ParticleChase command - set
        default:      op
      particlechase.cmd.remove:
        description:  ParticleChase command - remove
        default:      op
      particlechase.cmd.list:
        description:  ParticleChase command - list
        default:      op
...
