---
name:             ParticleChase
main:             presentkim\particlechase\ParticleChase
version:          1.2.1
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/ParticleChase
description:      A plugin set particle fallow player

permissions:
  particlechase.cmd:
    description:  ParticleChase main command
    default:      op
    children:
      particlechase.cmd.set:
        description:  ParticleChase command - set
        default:      op
      particlechase.cmd.remove:
        description:  ParticleChase command - remove
        default:      op
      particlechase.cmd.list:
        description:  ParticleChase command - list
        default:      op
      particlechase.cmd.lang:
        description:  ParticleChase command - lang
        default:      op
      particlechase.cmd.reload:
        description:  ParticleChase command - reload
        default:      op
      particlechase.cmd.save:
        description:  ParticleChase command - save
        default:      op
...
